In [49]:
import pandas as pd
import numpy as np

In [50]:
df = pd.read_csv("tmdb_reviews_fast.csv")

In [51]:
def rating_category(rating):
    if pd.isna(rating):
        return "unknown"
    elif rating >= 7:
        return "positive"
    elif rating <= 4:
        return "negative"
    else:
        return "neutral"

In [52]:
df["label"] = df["rating"].apply(rating_category)
df.shape

(7893, 9)

In [53]:
len(df[df["label"] == "unknown"]["review"])

958

In [54]:
# remove unknown samples
known_df = df[df["label"] != "unknown"]
print(known_df.shape)

(6935, 9)

In [55]:
known_df["label"].value_counts()

label
positive    4476
neutral     1632
negative     827
Name: count, dtype: int64

In [56]:
known_df.head(20)

,movie_id,movie_title,category,review_id,author,review,rating,created_at,label
0,1198994,Send Help,"Horror, Thriller, Comedy",6975ac2f6d953ac475a37f7b,JPV852,Pretty fun dark comedy-horror that features tw...,7.0,2026-01-25T05:37:51.965Z,positive
1,1198994,Send Help,"Horror, Thriller, Comedy",697cc71900ae4d242df95faf,Chris Sawin,"Gushing with frenetic humor, two magnificently...",8.0,2026-01-30T14:58:33.242Z,positive
2,1198994,Send Help,"Horror, Thriller, Comedy",69822f2ff5a8a6a8b3705862,Manuel São Bento,Full review: https://movieswetextedabout.com/s...,7.0,2026-02-03T17:23:59.424Z,positive
3,1198994,Send Help,"Horror, Thriller, Comedy",6987553dec6d453a583a98c0,Dean,"Sam Raimi’s Send Help is a brilliant, twisted ...",9.0,2026-02-07T15:07:42.027Z,positive
4,1198994,Send Help,"Horror, Thriller, Comedy",698761e2935f32a1abc1c369,Chandler Danier,Raimi is a good director. He has directed a go...,6.0,2026-02-07T16:01:38.347Z,neutral
5,1198994,Send Help,"Horror, Thriller, Comedy",698cced895efac1ec2425e0e,CinemaSerf,The spirit of “Nine to Five” (1980) is alive a...,7.0,2026-02-11T18:47:52.236Z,positive
6,1198994,Send Help,"Horror, Thriller, Comedy",69ca39be892f7916a9263970,GAHKWS,THIS IS NOT A BAD MOVIE. THE MAIN CHARACTER HA...,7.0,2026-03-30T08:52:14.451Z,positive
7,1226863,The Super Mario Galaxy Movie,"Family, Comedy, Adventure, Fantasy, Animation",69cc1afe574f58b99cc35932,Manuel São Bento,Full review: https://fandomwire.com/the-super-...,7.0,2026-03-31T19:05:34.222Z,positive
8,1226863,The Super Mario Galaxy Movie,"Family, Comedy, Adventure, Fantasy, Animation",69cd7fa7b40785ab8ba636ee,Suhaixy,**A film that could have had great potential**...,5.0,2026-04-01T20:27:19.654Z,neutral
9,1226863,The Super Mario Galaxy Movie,"Family, Comedy, Adventure, Fantasy, Animation",69cfe03046af586a52d2913b,Chandler Danier,This movie is stupid trash. You should know th...,8.0,2026-04-03T15:43:44.169Z,positive
11,1226863,The Super Mario Galaxy Movie,"Family, Comedy, Adventure, Fantasy, Animation",69d46b9f7de67d18b4edf321,certifiedcritic,It was engaging from start to finish.\r\n\r\nM...,9.0,2026-04-07T02:27:43.804Z,positive
12,1226863,The Super Mario Galaxy Movie,"Family, Comedy, Adventure, Fantasy, Animation",69df4cf1f6dafa2d54211a2b,CinemaSerf,Now I know that I'm not really the demographic...,5.0,2026-04-15T08:31:45.605Z,neutral
13,83533,Avatar: Fire and Ash,"Science Fiction, Adventure, Fantasy",6943d8d0a56edf751f705664,Manuel São Bento,FULL SPOILER-FREE REVIEW @ https://movieswetex...,5.0,2025-12-18T10:34:56.770Z,neutral
15,83533,Avatar: Fire and Ash,"Science Fiction, Adventure, Fantasy",69468cbad49dde55e5fb0ac4,Dean,"I give it 5/10 because, this 5 stars are for t...",5.0,2025-12-20T11:47:06.165Z,neutral
17,83533,Avatar: Fire and Ash,"Science Fiction, Adventure, Fantasy",694d0cb170129bc134b1be17,goinmental-33,I thought overall is really good movie which I...,8.0,2025-12-25T10:06:41.227Z,positive
18,83533,Avatar: Fire and Ash,"Science Fiction, Adventure, Fantasy",694d206014edd4da288eaf57,CinemaSerf,I suppose when you tell us all in advance that...,7.0,2025-12-25T11:30:40.808Z,positive
21,83533,Avatar: Fire and Ash,"Science Fiction, Adventure, Fantasy",69517c43032ef594a174e090,mutilator,Liked the film. It was not to long and not to ...,8.0,2025-12-28T18:51:47.758Z,positive
23,83533,Avatar: Fire and Ash,"Science Fiction, Adventure, Fantasy",69dfa8c20891932a1f3945b0,Chloe Jones,I watched Avatar 3 time: Fire & Ash and I'm gi...,9.0,2026-04-15T15:03:30.336Z,positive
24,1290821,Shelter,"Action, Crime, Thriller",69845a561eb4bd05d874ad1b,CinemaSerf,I’ve always loved the idea of living in a remo...,6.0,2026-02-05T08:52:38.056Z,neutral
25,1290821,Shelter,"Action, Crime, Thriller",6991409c02122c8a202871e8,MovieGuys,"""Shelter"" is, with one notable exception, a ra...",6.0,2026-02-15T03:42:20.818Z,neutral

In [57]:
known_df.to_csv("tmdb_reviews_labeled.csv", index=False)

In [58]:
from sklearn.utils.class_weight import compute_class_weight

weights = compute_class_weight(
    class_weight="balanced",
    classes=np.unique(known_df["label"]),
    y=known_df["label"]
)
weights

array([2.79524385, 1.41646242, 0.51645815])

In [59]:
min_class = known_df['label'].value_counts().min()

df_balanced = (
    known_df.groupby('label', group_keys=False)
    .sample(n=min_class, random_state=42)
)

df_balanced["label"].value_counts()

label
negative    827
neutral     827
positive    827
Name: count, dtype: int64

In [60]:
df_balanced.head(20)

,movie_id,movie_title,category,review_id,author,review,rating,created_at,label
2384,1100988,28 Years Later,"Horror, Thriller, Science Fiction",688f839217ad5cc979a466f1,Dean,Don't believe those reviews that give this mov...,1.0,2025-08-03T15:43:14.519Z,negative
7350,9355,Mad Max Beyond Thunderdome,"Action, Adventure, Science Fiction",5e950eebdb72c00019acafad,John Chard,Max Rockatansky and the Goonie feral gang.\r\n...,3.0,2020-04-14T01:16:27.217Z,negative
3091,760104,X,"Horror, Thriller",66d60acb5fdc67fbfec11dd4,tmdb51616167,I will be doing a combined review for the two ...,1.0,2024-09-02T18:58:19.001Z,negative
3834,181812,Star Wars: The Rise of Skywalker,"Adventure, Action, Science Fiction",5e7d5b0c13a320321727b9a2,Louisa Moore - Screen Zealots,"When it comes to “Star Wars,” being a fan come...",4.0,2020-03-27T01:46:52.373Z,negative
2049,419430,Get Out,"Mystery, Thriller, Horror",674c6ab46bfb98c974ef644c,Dean,Racist movie from a racist director Jordan Pee...,1.0,2024-12-01T13:55:00.568Z,negative
2797,505642,Black Panther: Wakanda Forever,"Action, Adventure, Science Fiction",640cda9d323eba00844946b5,GenerationofSwine,I want to first state that I am absolutely thr...,1.0,2023-03-11T19:46:37.188Z,negative
7783,196,Back to the Future Part III,"Adventure, Comedy, Science Fiction",6471c8e18813e401452ccc37,Rob,"Maybe a little better than the second movie, b...",4.0,2023-05-27T09:09:53.370Z,negative
980,438631,Dune,"Science Fiction, Adventure",68efbe111da0251cd5f96cab,Muhammad_Algabrouny,Seems like a glorified prologue to a stunning ...,4.0,2025-10-15T15:30:25.950Z,negative
2984,791373,Zack Snyder's Justice League,"Action, Adventure, Fantasy",60742314d4b9d900792149d9,iselates,I don't understand why people are getting so h...,4.0,2021-04-12T10:38:12.811Z,negative
7379,758323,The Pope's Exorcist,"Horror, Thriller",652c95c1024ec8011e343de3,hollowguy88,An episode of supernatural would've done a bet...,1.0,2023-10-16T01:45:37.270Z,negative
2646,558449,Gladiator II,"Action, Adventure, Drama",6779294438d26a2a63727c7d,FerdinandoLM,"$250 million, and the best we get is… rabid mo...",4.0,2025-01-04T12:27:48.204Z,negative
1649,1197306,A Working Man,"Action, Crime, Thriller",67eb57fad9981fda187aa48d,MovieGuys,"""A working Man"" is an accidental satire, of th...",3.0,2025-04-01T03:05:30.293Z,negative
7430,36643,The World Is Not Enough,"Adventure, Action, Thriller",643e1360e0ca7f053306c7bc,drystyx,This begins the total collapse of Bond films.\...,1.0,2023-04-18T03:49:52.755Z,negative
3441,330457,Frozen II,"Family, Animation, Adventure, Comedy, Fantasy",5f238d40eea34d00373953a3,tmdb92312096,Exactly what one can expect from a Disney prin...,4.0,2020-07-31T03:17:20.532Z,negative
313,1234821,Jurassic World Rebirth,"Science Fiction, Adventure, Action",69765c894fb48db33408878f,daniel_carr,Well the start of the movies was better than t...,4.0,2026-01-25T18:10:17.394Z,negative
4739,9732,The Lion King II: Simba's Pride,"Family, Adventure, Animation, Drama, Romance",59168b62c3a3683a930281fb,Gimly,If the first is Hamlet with lions then this on...,4.0,2017-05-13T04:28:18.495Z,negative
3709,339403,Baby Driver,"Action, Crime",6309acb3bb070d007c55e49d,tmdb28039023,There is an episode of Tales from the Crypt wh...,1.0,2022-08-27T05:33:39.562Z,negative
6286,570670,The Invisible Man,"Thriller, Science Fiction, Horror",5eae02800b7316001c3ebd15,Trazbor O'Gukguk,This is a film that tries to be smart and clea...,1.0,2020-05-02T23:30:08.834Z,negative
2441,297802,Aquaman,"Action, Adventure, Fantasy",5d7b0f05af4324521a97f49f,Snapcase,I am so conflicted.\r\nWe're introduced to the...,4.0,2019-09-13T03:37:41.274Z,negative
5287,331482,Little Women,"Drama, Romance",5e215062bfeb8b0015ce091e,Gimly,Guess 2019's just the year for Florence Pugh t...,4.0,2020-01-17T06:12:50.785Z,negative