In [31]:
import pandas as pd
import numpy as np

In [32]:
df = pd.read_csv("tmdb_reviews_balanced.csv")

In [33]:
def rating_category(rating):
    if pd.isna(rating):
        return "unknown"
    elif rating >= 7:
        return "positive"
    elif rating <= 4:
        return "negative"
    else:
        return "neutral"

In [34]:
df["sentiment"] = df["rating"].apply(rating_category)
df.shape

(4998, 9)

In [35]:
len(df[df["sentiment"] == "unknown"]["review"])

0

In [36]:
# remove unknown samples
known_df = df[df["sentiment"] != "unknown"]
print(known_df.shape)

(4998, 9)

In [37]:
known_df["sentiment"].value_counts()

sentiment
positive    1666
neutral     1666
negative    1666
Name: count, dtype: int64

In [38]:
known_df.sample(20)

,movie_id,movie_title,category,review_id,author,review,rating,created_at,sentiment
2987,949423,Pearl,"Horror, Thriller",641c7166d75bd6245aa7fc7a,CinemaSerf,Despite quite a characterful effort from Mia G...,6.0,2023-03-23T15:33:58.944Z,neutral
493,1184918,The Wild Robot,"Family, Animation, Science Fiction, Adventure",670684b4a88614d6b08af58b,Brent Marchant,There are times in our lives when nearly all o...,7.0,2024-10-09T13:27:16.982Z,positive
287,1061474,Superman,"Science Fiction, Adventure, Action",6884cea722300a50a772e624,Chris Sawin,The version of Superman in James Gunn’s film d...,8.0,2025-07-26T12:48:39.616Z,positive
1458,335983,Venom,"Science Fiction, Action",62dfa83733ad8f01bd501b26,Martha,I loved this I have been a huge Venom fan sinc...,8.0,2022-07-26T08:39:19.279Z,positive
913,76341,Mad Max: Fury Road,"Action, Adventure, Science Fiction",5990b254925141675f0322f9,simonTheDiver,I was never a fan of the original Mad Max film...,10.0,2017-08-13T20:11:00.604Z,positive
4794,43539,The Next Three Days,"Romance, Drama, Thriller, Crime",51d4755019c29567c308c54d,TheCakerBaker,If Paul Haggis is going to keep on making movi...,1.0,2013-07-03T19:02:40.442Z,negative
3171,758323,The Pope's Exorcist,"Horror, Thriller",6437e3ad81a7fc01277121cd,CinemaSerf,Based on a real character from the murkier sid...,6.0,2023-04-13T11:12:45.293Z,neutral
2396,282035,The Mummy,"Fantasy, Thriller, Action, Adventure, Horror",59f2febb925141229100c9c7,Dark Jedi,In view of the reviews this movie has received...,6.0,2017-10-27T09:39:07.666Z,neutral
1817,519182,Despicable Me 4,"Family, Comedy, Animation, Science Fiction, Ac...",669625e9ab87253c1ff3b0fa,CinemaSerf,"If it's not sacrilegious to say, I think this ...",6.0,2024-07-16T07:48:57.825Z,neutral
284,1061474,Superman,"Science Fiction, Adventure, Action",68728d02e467830aac105579,Manuel São Bento,FULL SPOILER-FREE REVIEW @ https://talkingfilm...,8.0,2025-07-12T16:27:46.426Z,positive
4495,599975,Countdown,"Horror, Thriller",5ead0abd1a934f0020e856b5,ceefoo,As a fan of Final Destination (2000) I approac...,1.0,2020-05-02T05:53:01.185Z,negative
1232,926393,The Equalizer 3,"Action, Thriller, Crime",65641b80244182010cb5b5d6,JPV852,Another solid entry in this franchise. Nothing...,7.0,2023-11-27T04:30:56.547Z,positive
3437,1448560,Wildcat,"Action, Thriller",692a718c8969e54eab3ce488,MovieGuys,"Kate Beckinsale's lead character, Ada is about...",4.0,2025-11-29T04:07:40.359Z,negative
847,603692,John Wick: Chapter 4,"Action, Thriller, Crime",6424f9e437b3a90077a25a53,EthicalAndroid,John Wick: Chapter 4\r\n\r\nScreenplay: John W...,10.0,2023-03-30T02:54:29.007Z,positive
3689,760104,X,"Horror, Thriller",66d60acb5fdc67fbfec11dd4,tmdb51616167,I will be doing a combined review for the two ...,1.0,2024-09-02T18:58:19.001Z,negative
74,634649,Spider-Man: No Way Home,"Action, Adventure, Science Fiction",62588a74c92c5d00652ee366,JPV852,Good addition to the Spider-Man franchise and ...,8.0,2022-04-14T20:56:20.593Z,positive
2727,11130,The Princess Diaries 2: Royal Engagement,"Comedy, Drama, Family, Romance",5f2b50c1f1759c003789771b,Kamurai,"Good watch, could watch again, but can't recom...",6.0,2020-08-06T00:37:21.662Z,neutral
341,603,The Matrix,"Action, Science Fiction",51ea49fe760ee35ab1463677,NeoBrowser,"Get this: what if all we know as reality was, ...",10.0,2013-07-20T08:27:42.076Z,positive
2310,577922,Tenet,"Action, Thriller, Science Fiction",652a8fb4024ec800e4448c4a,James,"Fine, but next time with subtitles.",5.0,2023-10-14T12:55:16.997Z,neutral
125,299536,Avengers: Infinity War,"Adventure, Action, Science Fiction",5ae866939251410cdc016c31,Movie Queen41,"Massive, epic movie. I'm so happy that Marvel ...",8.0,2018-05-01T13:07:31.580Z,positive

In [39]:
known_df.to_csv("tmdb_reviews_labeled.csv", index=False)

In [58]:
from sklearn.utils.class_weight import compute_class_weight

weights = compute_class_weight(
    class_weight="balanced",
    classes=np.unique(known_df["label"]),
    y=known_df["label"]
)
weights

array([2.79524385, 1.41646242, 0.51645815])

In [59]:
min_class = known_df['label'].value_counts().min()

df_balanced = (
    known_df.groupby('label', group_keys=False)
    .sample(n=min_class, random_state=42)
)

df_balanced["label"].value_counts()

label
negative    827
neutral     827
positive    827
Name: count, dtype: int64

In [ ]:
df_balanced

,movie_id,movie_title,category,review_id,author,review,rating,created_at,label
2384,1100988,28 Years Later,"Horror, Thriller, Science Fiction",688f839217ad5cc979a466f1,Dean,Don't believe those reviews that give this mov...,1.0,2025-08-03T15:43:14.519Z,negative
7350,9355,Mad Max Beyond Thunderdome,"Action, Adventure, Science Fiction",5e950eebdb72c00019acafad,John Chard,Max Rockatansky and the Goonie feral gang.\r\n...,3.0,2020-04-14T01:16:27.217Z,negative
3091,760104,X,"Horror, Thriller",66d60acb5fdc67fbfec11dd4,tmdb51616167,I will be doing a combined review for the two ...,1.0,2024-09-02T18:58:19.001Z,negative
3834,181812,Star Wars: The Rise of Skywalker,"Adventure, Action, Science Fiction",5e7d5b0c13a320321727b9a2,Louisa Moore - Screen Zealots,"When it comes to “Star Wars,” being a fan come...",4.0,2020-03-27T01:46:52.373Z,negative
2049,419430,Get Out,"Mystery, Thriller, Horror",674c6ab46bfb98c974ef644c,Dean,Racist movie from a racist director Jordan Pee...,1.0,2024-12-01T13:55:00.568Z,negative
2797,505642,Black Panther: Wakanda Forever,"Action, Adventure, Science Fiction",640cda9d323eba00844946b5,GenerationofSwine,I want to first state that I am absolutely thr...,1.0,2023-03-11T19:46:37.188Z,negative
7783,196,Back to the Future Part III,"Adventure, Comedy, Science Fiction",6471c8e18813e401452ccc37,Rob,"Maybe a little better than the second movie, b...",4.0,2023-05-27T09:09:53.370Z,negative
980,438631,Dune,"Science Fiction, Adventure",68efbe111da0251cd5f96cab,Muhammad_Algabrouny,Seems like a glorified prologue to a stunning ...,4.0,2025-10-15T15:30:25.950Z,negative
2984,791373,Zack Snyder's Justice League,"Action, Adventure, Fantasy",60742314d4b9d900792149d9,iselates,I don't understand why people are getting so h...,4.0,2021-04-12T10:38:12.811Z,negative
7379,758323,The Pope's Exorcist,"Horror, Thriller",652c95c1024ec8011e343de3,hollowguy88,An episode of supernatural would've done a bet...,1.0,2023-10-16T01:45:37.270Z,negative
2646,558449,Gladiator II,"Action, Adventure, Drama",6779294438d26a2a63727c7d,FerdinandoLM,"$250 million, and the best we get is… rabid mo...",4.0,2025-01-04T12:27:48.204Z,negative
1649,1197306,A Working Man,"Action, Crime, Thriller",67eb57fad9981fda187aa48d,MovieGuys,"""A working Man"" is an accidental satire, of th...",3.0,2025-04-01T03:05:30.293Z,negative
7430,36643,The World Is Not Enough,"Adventure, Action, Thriller",643e1360e0ca7f053306c7bc,drystyx,This begins the total collapse of Bond films.\...,1.0,2023-04-18T03:49:52.755Z,negative
3441,330457,Frozen II,"Family, Animation, Adventure, Comedy, Fantasy",5f238d40eea34d00373953a3,tmdb92312096,Exactly what one can expect from a Disney prin...,4.0,2020-07-31T03:17:20.532Z,negative
313,1234821,Jurassic World Rebirth,"Science Fiction, Adventure, Action",69765c894fb48db33408878f,daniel_carr,Well the start of the movies was better than t...,4.0,2026-01-25T18:10:17.394Z,negative
4739,9732,The Lion King II: Simba's Pride,"Family, Adventure, Animation, Drama, Romance",59168b62c3a3683a930281fb,Gimly,If the first is Hamlet with lions then this on...,4.0,2017-05-13T04:28:18.495Z,negative
3709,339403,Baby Driver,"Action, Crime",6309acb3bb070d007c55e49d,tmdb28039023,There is an episode of Tales from the Crypt wh...,1.0,2022-08-27T05:33:39.562Z,negative
6286,570670,The Invisible Man,"Thriller, Science Fiction, Horror",5eae02800b7316001c3ebd15,Trazbor O'Gukguk,This is a film that tries to be smart and clea...,1.0,2020-05-02T23:30:08.834Z,negative
2441,297802,Aquaman,"Action, Adventure, Fantasy",5d7b0f05af4324521a97f49f,Snapcase,I am so conflicted.\r\nWe're introduced to the...,4.0,2019-09-13T03:37:41.274Z,negative
5287,331482,Little Women,"Drama, Romance",5e215062bfeb8b0015ce091e,Gimly,Guess 2019's just the year for Florence Pugh t...,4.0,2020-01-17T06:12:50.785Z,negative